[build]
base = "blast-bot-js"              # subfolder project bot kamu
functions = "netlify/functions"    # relatif terhadap base
command = "npm install"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
